[[headers]]
  for = "/*"
  [headers.values]
     Content-Security-Policy = "img-src 'self' blob: data:; upgrade-insecure-requests; script-src  'sha256-test'"
    
[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    path = "/*"
    reportOnly = false
