[[plugins]]
  package = "@netlify/plugin-csp-nonce"

  [plugins.inputs]
    path = "/*"
    reportOnly = false

    [plugins.inputs.cspDirectives]
      default-src = "'self'"
      script-src = "'self' 'nonce-{{nonce}}'"
      style-src = "'self' 'unsafe-inline'"
      img-src = "'self' https://trusted-image-source.com"
      object-src = "'none'"
      frame-src = "'none'"
