[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    path = "/*"
    reportOnly = false
    excludedPath = [
      "/api/*",
      "**/*.bespoke.extension"
    ]

[[edge_functions]]
  function = "csp"
  path = "/*"
