import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const generateNonce = () => {
  return Buffer.from(crypto.randomUUID()).toString("base64"); // Generate a secure nonce
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = generateNonce();
  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content={`
            default-src 'self';
            object-src 'none';
            script-src 'self' 'nonce-${nonce}';
            style-src 'self' 'unsafe-inline';
            img-src 'self' data:;
            font-src 'self' data:;
            connect-src 'self' https:;
            frame-src 'none';
            base-uri 'self';
            form-action 'self';
          `}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
